server:
  port: port

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password

payment:
  coin-remitter:
    currency: USD
    expireTime: 60
    notifyUrl: notifyUrl
    secretKey: secretKey
    invoiceUrl: invoiceUrl
    qrUrl: https://chart.googleapis.com/chart
    coins:
      TCN:
        name: TCN
        qrName: something
        api-key: api-key
        password: password
      BTC:
        name: BTC
        qrName: bitcoin
        api-key: api-key
        password: password

auth:
  token:
    secret: secret-key
    auth-expiration: 36000000000
    refresh-expiration: 365000000000
  validation:
    verify:
      secretKey: secretKey
      url: url
    restore:
      secretKey: secretKey
      url: url

reserve-modem:
  cost: cost

mail:
  validation:
    smtp:
      host: host
      username: username
      password: password
      port: port
      protocol: smtp
  debug: true