package com.example.SmsValidator.socket;

import lombok.AllArgsConstructor;
import lombok.Getter;

public class CountryFind {
    public static Country findCountry(String imsiCountryCode) {
        return switch (imsiCountryCode) {
            case "412" -> new Country("Afganistan", "+93");
            case "276" -> new Country("Albania", "+355");
            case "603" -> new Country("Algeria", "+213");
            case "544" -> new Country("American Samoa", "+1684");
            case "213" -> new Country("Andorra", "+376");
            case "631" -> new Country("Angola", "+244");
            case "365" -> new Country("Anguilla", "+1264");
            case "344" -> new Country("Antigua and Barbuda", "+1268");
            case "722" -> new Country("Argentina", "+54");
            case "283" -> new Country("Armenia", "+374");
            case "363" -> new Country("Aruba", "+297");
            case "505" -> new Country("Australia", "+61");
            case "232" -> new Country("Austria", "+43");
            case "400" -> new Country("Azerbaijan", "+994");
            case "364" -> new Country("Bahamas", "+1242");
            case "426" -> new Country("Bahrain", "+973");
            case "470" -> new Country("Bangladesh", "+880");
            case "342" -> new Country("Barbados", "+1246");
            case "257" -> new Country("Belarus", "+375");
            case "206" -> new Country("Belgium", "+32");
            case "702" -> new Country("Belize", "+501");
            case "616" -> new Country("Benin", "+229");
            case "350" -> new Country("Bermuda", "+1441");
            case "402" -> new Country("Bhutan", "+975");
            case "736" -> new Country("Bolivia", "+591");
            case "218" -> new Country("Bosnia and Herzegovina", "+387");
            case "652" -> new Country("Botswana", "+267");
            case "724" -> new Country("Brazil", "+55");
            case "348" -> new Country("British Virgin Islands", "+1284");
            case "528" -> new Country("Brunei Darussalam", "+673");
            case "284" -> new Country("Bulgaria", "+359");
            case "613" -> new Country("Burkina Faso", "+226");
            case "642" -> new Country("Burundi", "+257");
            case "456" -> new Country("Cambodia", "+855");
            case "624" -> new Country("Cameroon", "+237");
            case "302" -> new Country("Canada", "+1");
            case "625" -> new Country("Cape Verde", "+238");
            case "346" -> new Country("Cayman Islands", "+1345");
            case "623" -> new Country("Central African Republic", "+236");
            case "622" -> new Country("Chad", "+235");
            case "730" -> new Country("Chile", "+56");
            case "460" -> new Country("China", "+86");
            case "732" -> new Country("Colombia", "+57");
            case "654" -> new Country("Comoros and Mayotte", "+269");
            case "548" -> new Country("Cook Islands", "+682");
            case "712" -> new Country("Costa Rica", "+506");
            case "612" -> new Country("Côte d'Ivoire", "+225");
            case "219" -> new Country("Croatia", "+385");
            case "368" -> new Country("Cuba", "+53");
            case "280" -> new Country("Cyprus", "+357");
            case "230" -> new Country("Czech Rep.", "+420");
            case "630" -> new Country("Democratic Republic of the Congo", "+243");
            case "238" -> new Country("Denmark", "+45");
            case "638" -> new Country("Djibouti", "+253");
            case "366" -> new Country("Dominica", "+1767");
            case "370" -> new Country("Dominican Republic", "+1809");
            case "740" -> new Country("Ecuador", "+593");
            case "602" -> new Country("Egypt", "+20");
            case "706" -> new Country("El Salvador", "+503");
            case "627" -> new Country("Equatorial Guinea", "+240");
            case "657" -> new Country("Eritrea", "+291");
            case "248" -> new Country("Estonia", "+372");
            case "636" -> new Country("Ethiopia", "+251");
            case "750" -> new Country("Falkland Islands", "+500");
            case "288" -> new Country("Faroe Islands", "+298");
            case "542" -> new Country("Fiji", "+679");
            case "244" -> new Country("Finland", "+358");
            case "208" -> new Country("France", "+33");
            case "742" -> new Country("French Guiana", "+594");
            case "547" -> new Country("French Polynesia", "+689");
            case "628" -> new Country("Gabon", "+241");
            case "607" -> new Country("Gambia", "+220");
            case "282" -> new Country("Georgia", "+995");
            case "262" -> new Country("Germany", "+49");
            case "620" -> new Country("Ghana", "+233");
            case "266" -> new Country("Gibraltar", "+350");
            case "202" -> new Country("Greece", "+30");
            case "290" -> new Country("Greenland", "+299");
            case "352" -> new Country("Grenada", "+1473");
            case "535" -> new Country("Guam (US)", "+1671");
            case "704" -> new Country("Guatemala", "+502");
            case "611" -> new Country("Guinea", "+224");
            case "632" -> new Country("Guinea-Bissau", "+245");
            case "738" -> new Country("Guyana", "+592");
            case "372" -> new Country("Haiti", "+509");
            case "708" -> new Country("Honduras", "+504");
            case "454" -> new Country("Hongkong, China", "+852");
            case "216" -> new Country("Hungary", "+36");
            case "274" -> new Country("Iceland", "+354");
            case "404" -> new Country("India", "+91");
            case "405" -> new Country("India", "+91");
            case "510" -> new Country("Indonesia", "+62");
            case "-1" -> new Country("International", "+");
            case "901" -> new Country("International", "+");
            case "432" -> new Country("Iran", "+98");
            case "418" -> new Country("Iraq", "+964");
            case "272" -> new Country("Ireland", "+353");
            case "425" -> new Country("Israel", "+972");
            case "222" -> new Country("Italy", "+39");
            case "338" -> new Country("Jamaica", "+1876");
            case "440" -> new Country("Japan", "+81");
            case "441" -> new Country("Japan", "+81");
            case "416" -> new Country("Jordan", "+962");
            case "401" -> new Country("Kazakhstan", "+7");
            case "639" -> new Country("Kenya", "+254");
            case "545" -> new Country("Kiribati", "+686");
            case "467" -> new Country("Korea (North)", "+850");
            case "450" -> new Country("Korea (South)", "+82");
            case "419" -> new Country("Kuwait", "+965");
            case "437" -> new Country("Kyrqyzstan", "+996");
            case "457" -> new Country("Laos", "+856");
            case "247" -> new Country("Latvia", "+371");
            case "415" -> new Country("Lebanon", "+961");
            case "651" -> new Country("Lesotho", "+266");
            case "618" -> new Country("Liberia", "+231");
            case "606" -> new Country("Libya", "+218");
            case "295" -> new Country("Liechtenstein", "+423");
            case "246" -> new Country("Lithuania", "+370");
            case "270" -> new Country("Luxembourg", "+352");
            case "455" -> new Country("Macao China", "+853");
            case "294" -> new Country("Macedonia", "+389");
            case "646" -> new Country("Madagascar", "+261");
            case "650" -> new Country("Malawi", "+265");
            case "502" -> new Country("Malaysia", "+60");
            case "472" -> new Country("Maldives", "+960");
            case "610" -> new Country("Mali", "+223");
            case "278" -> new Country("Malta", "+356");
            case "551" -> new Country("Marshall Islands", "+692");
            case "340" -> new Country("Martinique & Guadeloupe", "+596");
            case "609" -> new Country("Mauritania", "+222");
            case "617" -> new Country("Mauritius", "+230");
            case "334" -> new Country("Mexico", "+52");
            case "550" -> new Country("Micronesia", "+691");
            case "259" -> new Country("Moldova", "+373");
            case "212" -> new Country("Monaco", "+377");
            case "428" -> new Country("Mongolia", "+976");
            case "297" -> new Country("Montenegro", "+382");
            case "354" -> new Country("Montserrat", "+1664");
            case "604" -> new Country("Morocco", "+212");
            case "643" -> new Country("Mozambique", "+258");
            case "414" -> new Country("Myanmar", "+95");
            case "649" -> new Country("Namibia", "+264");
            case "536" -> new Country("Nauru", "+674");
            case "429" -> new Country("Nepal", "+977");
            case "204" -> new Country("Netherlands", "+31");
            case "362" -> new Country("Netherlands Antilles", "+599");
            case "546" -> new Country("New Caledonia", "+687");
            case "530" -> new Country("New Zealand", "+64");
            case "710" -> new Country("Nicaraqua", "+505");
            case "614" -> new Country("Niger", "+227");
            case "621" -> new Country("Nigeria", "+234");
            case "534" -> new Country("Northern Mariana Islands (US)", "+1670");
            case "242" -> new Country("Norway", "+47");
            case "422" -> new Country("Oman", "+968");
            case "410" -> new Country("Pakistan", "+92");
            case "552" -> new Country("Palau", "+680");
            case "423" -> new Country("Palestine", "+970");
            case "714" -> new Country("Panama", "+507");
            case "537" -> new Country("Papua New Guinea", "+675");
            case "744" -> new Country("Paraquay", "+595");
            case "716" -> new Country("Peru", "+51");
            case "515" -> new Country("Philippines", "+63");
            case "260" -> new Country("Poland", "+48");
            case "268" -> new Country("Portugal", "+351");
            case "330" -> new Country("Puerto Rico (US)", "+1787");
            case "427" -> new Country("Quatar", "+974");
            case "629" -> new Country("Republic of Congo", "+242");
            case "647" -> new Country("Reunion", "+262");
            case "226" -> new Country("Romania", "+40");
            case "250" -> new Country("Russian Federation", "+7");
            case "635" -> new Country("Rwanda", "+250");
            case "356" -> new Country("Saint Kitts and Nevis", "+1869");
            case "358" -> new Country("Saint Lucia", "+1758");
            case "308" -> new Country("Saint Pierre and Miquelon", "+508");
            case "360" -> new Country("Saint Vincent and the Grenadines", "+1784");
            case "549" -> new Country("Samoa", "+685");
            case "292" -> new Country("San Marino", "+378");
            case "626" -> new Country("Sao Tome and Principe", "+239");
            case "420" -> new Country("Saudi Arabia", "+966");
            case "608" -> new Country("Senegal", "+221");
            case "220" -> new Country("Serbia & Montenegro", "+381");
            case "633" -> new Country("Seychelles", "+248");
            case "619" -> new Country("Sierra Leone", "+232");
            case "525" -> new Country("Singapore", "+65");
            case "231" -> new Country("Slovakia", "+421");
            case "293" -> new Country("Slovenia", "+386");
            case "540" -> new Country("Solomon Islands", "+677");
            case "637" -> new Country("Somalia", "+252");
            case "655" -> new Country("South Africa", "+27");
            case "214" -> new Country("Spain", "+34");
            case "413" -> new Country("Sri Lanka", "+94");
            case "634" -> new Country("Sudan", "+249");
            case "746" -> new Country("Suriname", "+597");
            case "653" -> new Country("Swaziland", "+268");
            case "240" -> new Country("Sweden", "+46");
            case "228" -> new Country("Switzerland", "+41");
            case "417" -> new Country("Syrian Arab Republic", "+963");
            case "466" -> new Country("Taiwan", "+886");
            case "436" -> new Country("Tajikistan", "+992");
            case "640" -> new Country("Tanzania", "+255");
            case "520" -> new Country("Thailand", "+66");
            case "514" -> new Country("Timor-Leste (East Timor)", "+640");
            case "615" -> new Country("Togo", "+228");
            case "539" -> new Country("Tonga", "+676");
            case "374" -> new Country("Trinidad and Tobago", "+1868");
            case "605" -> new Country("Tunisia", "+216");
            case "286" -> new Country("Turkey", "+90");
            case "438" -> new Country("Turkmenistan", "+993");
            case "376" -> new Country("Turks and Caicos Islands (UK)", "+1649");
            case "641" -> new Country("Uganda", "+256");
            case "234" -> new Country("UK", "+44");
            case "235" -> new Country("UK", "+44");
            case "255" -> new Country("Ukraine", "+380");
            case "424" -> new Country("United Arab Emirates", "+971");
            case "430" -> new Country("United Arab Emirates", "+971");
            case "431" -> new Country("United Arab Emirates", "+971");
            case "310" -> new Country("United States", "+1");
            case "316" -> new Country("United States", "+1");
            case "311" -> new Country("United States", "+1");
            case "748" -> new Country("Uruguay", "+598");
            case "332" -> new Country("US Virgin Islands", "+1340");
            case "434" -> new Country("Uzbekistan", "+998");
            case "541" -> new Country("Vanuatu", "+678");
            case "225" -> new Country("Vatican City State", "+379");
            case "734" -> new Country("Venezuela", "+58");
            case "452" -> new Country("Vietnam", "+84");
            case "543" -> new Country("Wallis and Futuna (France)", "+681");
            case "421" -> new Country("Yemen", "+967");
            case "645" -> new Country("Zambia", "+260");
            case "648" -> new Country("Zimbabwe", "+263");
            default -> new Country(null, null);
        };
    }

    @AllArgsConstructor
    @Getter
    public static class Country {
        private String countryName;
        private String countryCode;
    }
}
